### ISSUE TITLE
Dune Error

### ISSUE THREAD

**Issue by rnrand** [inQWIRE/openqasm-parser#1]
I've been trying to install the openQASM parser (via opam) on my new computer and I'm getting the following error:

```
[ERROR] The compilation of openQASM failed at
        "/Users/rand/.opam/opam-init/hooks/sandbox.sh build dune build -p
        openQASM -j 7 @install".

#=== ERROR while compiling openQASM.0.3.0 =====================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.08.0 | https://opam.ocaml.org#6d7fcbc5
# path        ~/.opam/default/.opam-switch/build/openQASM.0.3.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p openQASM -j 7 @install
# exit-code   1
# env-file    ~/.opam/log/openQASM-41863-6d07ae.env
# output-file ~/.opam/log/openQASM-41863-6d07ae.out
### output ###
# File "dune-project", line 1, characters 11-14:
# 1 | (lang dune 2.0)
#                ^^^
# Error: Version 2.0 of dune is not supported.
# Supported versions:
# - 0.0
# - 1.0 to 1.11
```

This is odd, as the documentation currently says it requires Dune > 1.5

**Comment by k4rtik** [comment]
(I edited your comment to avoid weird markdown rendering.)

This is odd as you seem to be using OCaml 4.08.0. When I tested it for merge to opam repo, I had switched to dune 2.0 lang because only compilers lower than 4.07 didn't support the higher version 2.1 that I was using earlier, see: https://github.com/ocaml/opam-repository/pull/15677#issuecomment-575101543

I just tested it on my macOS machine as follows and it worked fine:
```
$ opam switch create 4.08.0
[...]
$ eval $(opam env)
[...]
$ opam install openQASM
[...]
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed dune.2.6.1
∗ installed menhirSdk.20200624
∗ installed menhirLib.20200624
∗ installed menhir.20200624
∗ installed openQASM.0.3.0
Done.
$
```

I wonder if it's some environment issue on your machine. Can you try in a fresh environment or double check your opam env, perhaps the environment file `~/.opam/log/openQASM-41863-6d07ae.env` above has some info?

**Comment by k4rtik** [comment]
Hi @rnrand, did this issue resolve for you?
